# Generated by Django 3.1.4 on 2020-12-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemlists', '0002_auto_20201211_2246'),
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='problems',
            field=models.ManyToManyField(blank=True, null=True, related_name='Problem', to='problemlists.Problem'),
        ),
    ]
