# Generated by Django 3.1.4 on 2020-12-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201212_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='codeforces',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
