# Generated by Django 3.1.4 on 2020-12-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201212_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='codeforces',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
