# Generated by Django 3.1.4 on 2020-12-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201212_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='atcoder',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='codechef',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='spoj',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uva_handle',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uva_id',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
