# Generated by Django 3.1.4 on 2020-12-17 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topicwise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solved',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topicwise.problem'),
        ),
        migrations.AlterField(
            model_name='solved',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
